steps: 
-  name: 'gcr.io/cloud-builders/git'
   args: ['clone', 'https://github.com/oil78/repo-5.git']

-  name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}', '.']

-  name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}', '.']

substitutions:
   PROJECT_ID : kubernetestest-494210
   CINAME : gke-image
   VERSION : v1.0